[project]
name = "ietf-notebook"
dynamic = ["version"]
authors = [
    {name="Mark Nottingham", email="mnot@mnot.net"}
]
description = "Gather resources for an IETF Working Group for use in NotebookLM"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE.md"]
classifiers = [
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta"
]

dependencies = [
    "requests",
    "beautifulsoup4",
    "google-auth",
    "google-auth-oauthlib",
    "google-auth-httplib2",
]

[project.optional-dependencies]
certs = ["pip-system-certs"]
dev = [
    "mypy",
    "black",
    "pylint",
    "pytest",
    "pytest-md",
    "validate-pyproject",
    "build",
    "types-requests",
    "types-beautifulsoup4"
]

[project.urls]
homepage = "https://github.com/mnot/ietf-notebook"

[project.scripts]
ietf-notebook = "ietf_notebook.__main__:main"


[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "ietf_notebook.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["ietf_notebook", "ietf_notebook.*"]
namespaces = false

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
ietf_notebook = ["py.typed"]

